/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.a3.testpsc;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author layon
 */
public class ListCardMenu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ListCardMenu() {
        initComponents();
        Atributo.setBackground(new Color(0, 0, 0, 1));
        jTextFieldNumero.setBackground(new Color(0, 0, 0, 1));
        NomeCard.setBackground(new Color(0, 0, 0, 1));
        Efeito.setBackground(new Color(0, 0, 0, 1));
        Tipo.setBackground(new Color(0, 0, 0, 1));
        Nivel.setBackground(new Color(0, 0, 0, 1));
        Ataque.setBackground(new Color(0, 0, 0, 1));
        Defesa.setBackground(new Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Esquerda = new javax.swing.JButton();
        Direita = new javax.swing.JButton();
        Atributo = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        Efeito = new javax.swing.JTextField();
        Tipo = new javax.swing.JTextField();
        Nivel = new javax.swing.JTextField();
        Ataque = new javax.swing.JTextField();
        Defesa = new javax.swing.JTextField();
        NomeCard = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Esquerda.setBorder(null);
        Esquerda.setBorderPainted(false);
        Esquerda.setContentAreaFilled(false);
        Esquerda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsquerdaActionPerformed(evt);
            }
        });
        getContentPane().add(Esquerda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 120, 120));

        Direita.setBorder(null);
        Direita.setBorderPainted(false);
        Direita.setContentAreaFilled(false);
        Direita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireitaActionPerformed(evt);
            }
        });
        getContentPane().add(Direita, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 120, 110));

        Atributo.setForeground(new java.awt.Color(255, 255, 255));
        Atributo.setBorder(null);
        Atributo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Atributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtributoActionPerformed(evt);
            }
        });
        getContentPane().add(Atributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 180, 30));

        jTextFieldNumero.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNumero.setBorder(null);
        jTextFieldNumero.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 80, 30));

        Efeito.setForeground(new java.awt.Color(255, 255, 255));
        Efeito.setBorder(null);
        Efeito.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Efeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfeitoActionPerformed(evt);
            }
        });
        getContentPane().add(Efeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 180, 30));

        Tipo.setForeground(new java.awt.Color(255, 255, 255));
        Tipo.setBorder(null);
        Tipo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 180, 30));

        Nivel.setForeground(new java.awt.Color(255, 255, 255));
        Nivel.setBorder(null);
        Nivel.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelActionPerformed(evt);
            }
        });
        getContentPane().add(Nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 180, 30));

        Ataque.setForeground(new java.awt.Color(255, 255, 255));
        Ataque.setBorder(null);
        Ataque.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 180, 30));

        Defesa.setForeground(new java.awt.Color(255, 255, 255));
        Defesa.setBorder(null);
        Defesa.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Defesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefesaActionPerformed(evt);
            }
        });
        getContentPane().add(Defesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 180, 30));

        NomeCard.setForeground(new java.awt.Color(255, 255, 255));
        NomeCard.setBorder(null);
        NomeCard.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        NomeCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCardActionPerformed(evt);
            }
        });
        getContentPane().add(NomeCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Facul USJT\\Programaçao de Software\\Projeto A3\\Imagens\\ListCard.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsquerdaActionPerformed
        
    }//GEN-LAST:event_EsquerdaActionPerformed

    private void DireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireitaActionPerformed

    private void AtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtributoActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void EfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfeitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EfeitoActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NivelActionPerformed

    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtaqueActionPerformed

    private void DefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefesaActionPerformed

    private void NomeCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListCardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ataque;
    private javax.swing.JTextField Atributo;
    private javax.swing.JTextField Defesa;
    private javax.swing.JButton Direita;
    private javax.swing.JTextField Efeito;
    private javax.swing.JButton Esquerda;
    private javax.swing.JTextField Nivel;
    private javax.swing.JTextField NomeCard;
    private javax.swing.JTextField Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
