/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.a3.testpsc;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author layon
 */
public class UpdateCardMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCadastro
     */
    public UpdateCardMenu() {
        initComponents();
        jTextFieldNome.setBackground(new Color(0, 0, 0, 1));
        jTextFieldTipo.setBackground(new Color(0, 0, 0, 1));
        jTextFieldAtri.setBackground(new Color(0, 0, 0, 1));
        jTextFieldEfeito.setBackground(new Color(0, 0, 0, 1));
        jTextFieldNivel.setBackground(new Color(0, 0, 0, 1));
        jTextFieldAtaque.setBackground(new Color(0, 0, 0, 1));
        jTextFieldDef.setBackground(new Color(0, 0, 0, 1));
        jTextFieldNumeroCarta.setBackground(new Color(0, 0, 0, 1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldEfeito = new javax.swing.JTextField();
        jTextFieldNivel = new javax.swing.JTextField();
        jTextFieldAtaque = new javax.swing.JTextField();
        jTextFieldDef = new javax.swing.JTextField();
        jTextFieldAtri = new javax.swing.JTextField();
        jTextFieldNumeroCarta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 140, 30));

        jTextFieldNome.setBorder(null);
        jTextFieldNome.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 30));

        jTextFieldTipo.setBorder(null);
        getContentPane().add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 40));

        jTextFieldEfeito.setBorder(null);
        jTextFieldEfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEfeitoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEfeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 210, 30));

        jTextFieldNivel.setBorder(null);
        jTextFieldNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNivelActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, 30));

        jTextFieldAtaque.setBorder(null);
        jTextFieldAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 210, 30));

        jTextFieldDef.setBorder(null);
        jTextFieldDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDefActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 210, 30));

        jTextFieldAtri.setBorder(null);
        jTextFieldAtri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtriActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAtri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 30));

        jTextFieldNumeroCarta.setBorder(null);
        jTextFieldNumeroCarta.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextFieldNumeroCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroCartaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumeroCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Facul USJT\\Programaçao de Software\\Projeto A3\\Imagens\\Minimenu4.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Cartas carta = new Cartas();
      CrudCarta crudCarta = new CrudCarta();
      CrudBD crudBD = new CrudBD();

// Verificação de campos vazios ou nulos
if (jTextFieldNumeroCarta.getText() == null || jTextFieldNumeroCarta.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Número da Carta' não pode estar vazio.");
    return;
}

if (jTextFieldNome.getText() == null || jTextFieldNome.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Nome' não pode estar vazio.");
    return;
}

if (jTextFieldTipo.getText() == null || jTextFieldTipo.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Tipo' não pode estar vazio.");
    return;
}

if (jTextFieldAtri.getText() == null || jTextFieldAtri.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Atributo' não pode estar vazio.");
    return;
}

if (jTextFieldEfeito.getText() == null || jTextFieldEfeito.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Efeito' não pode estar vazio.");
    return;
}

if (jTextFieldNivel.getText() == null || jTextFieldNivel.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Nível' não pode estar vazio.");
    return;
}

if (jTextFieldAtaque.getText() == null || jTextFieldAtaque.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Ataque' não pode estar vazio.");
    return;
}

if (jTextFieldDef.getText() == null || jTextFieldDef.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "O campo 'Defesa' não pode estar vazio.");
    return;
}

try {
    int numero = Integer.parseInt(jTextFieldNumeroCarta.getText());
    carta.setNumero(numero);
    
    carta.setNome(jTextFieldNome.getText());
    carta.setTipo(jTextFieldTipo.getText());
    carta.setAtributo(jTextFieldAtri.getText());
    carta.setEfeito(jTextFieldEfeito.getText());
    
    int nivel = Integer.parseInt(jTextFieldNivel.getText());
    carta.setNivel(nivel);
    
    int ataque = Integer.parseInt(jTextFieldAtaque.getText());
    carta.setAtaque(ataque);
    
    int defesa = Integer.parseInt(jTextFieldDef.getText());
    carta.setDefesa(defesa);

    
    crudCarta.UpdateCarta(carta);

    
    JOptionPane.showMessageDialog(null, "Carta atualizada com sucesso!");
    this.setVisible(false);
    
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Certifique-se de que os campos 'Número', 'Nível', 'Ataque' e 'Defesa' contenham apenas números.");
}

        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldEfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEfeitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEfeitoActionPerformed

    private void jTextFieldNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNivelActionPerformed

    private void jTextFieldAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtaqueActionPerformed

    private void jTextFieldDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDefActionPerformed

    private void jTextFieldAtriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtriActionPerformed

    private void jTextFieldNumeroCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldAtaque;
    private javax.swing.JTextField jTextFieldAtri;
    private javax.swing.JTextField jTextFieldDef;
    private javax.swing.JTextField jTextFieldEfeito;
    private javax.swing.JTextField jTextFieldNivel;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumeroCarta;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
